---
#configure apache2.conf and send copy.html file
  - name: apache2.conf file
    copy: src=apache2.conf dest=/etc/apache2/
    notify:
    - restart apache2 service
    
  - name: send copy.html file
    copy: src=index.html dest=/var/www/html/
